// Replace this with the file generated by `flutterfire configure`
// or paste the Firebase options for your project.
class DefaultFirebaseOptions {
  static get currentPlatform => throw UnimplementedError('Add firebase_options.dart generated by FlutterFire CLI');
}
