// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrPOA3R13eoaKy7N220yRQxEr9oJ-doKc',
    appId: '1:559812462196:web:45fde8fa3661c297b47321',
    messagingSenderId: '559812462196',
    projectId: 'swipeurmatch',
    authDomain: 'swipeurmatch.firebaseapp.com',
    storageBucket: 'swipeurmatch.firebasestorage.app',
    measurementId: 'G-TGXS17MKDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEYr68jeJ2aU60PaoQMavVJpQrpJNq-_g',
    appId: '1:559812462196:android:af41c779fa82581fb47321',
    messagingSenderId: '559812462196',
    projectId: 'swipeurmatch',
    storageBucket: 'swipeurmatch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOC5AqKmhSmVSvLdblRDT4a5sRRjUQPRg',
    appId: '1:559812462196:ios:ceea2830bfa9ecf0b47321',
    messagingSenderId: '559812462196',
    projectId: 'swipeurmatch',
    storageBucket: 'swipeurmatch.firebasestorage.app',
    androidClientId: '559812462196-236gg2ntc3jmtj5fpcao5kkp2qmsgm7q.apps.googleusercontent.com',
    iosClientId: '559812462196-fq3ifijo9cqb1294i53djsge4l9m4kdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipeurmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOC5AqKmhSmVSvLdblRDT4a5sRRjUQPRg',
    appId: '1:559812462196:ios:ceea2830bfa9ecf0b47321',
    messagingSenderId: '559812462196',
    projectId: 'swipeurmatch',
    storageBucket: 'swipeurmatch.firebasestorage.app',
    androidClientId: '559812462196-236gg2ntc3jmtj5fpcao5kkp2qmsgm7q.apps.googleusercontent.com',
    iosClientId: '559812462196-fq3ifijo9cqb1294i53djsge4l9m4kdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.swipeurmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrPOA3R13eoaKy7N220yRQxEr9oJ-doKc',
    appId: '1:559812462196:web:45fde8fa3661c297b47321',
    messagingSenderId: '559812462196',
    projectId: 'swipeurmatch',
    authDomain: 'swipeurmatch.firebaseapp.com',
    storageBucket: 'swipeurmatch.firebasestorage.app',
    measurementId: 'G-TGXS17MKDD',
  );
}
